## Analysis of the SAMHSA Mental Health Client-Level Data (MH-CLD) dataset

Downloaded as the "Delimited" version in the data folder with no renaming, then unzipped.

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats

In [4]:
# the common datapath; unzipped name of the data file (not renamed)
data = "data/mhcld_puf_2021.csv"

df = pd.read_csv(data)
df.head()

,YEAR,AGE,EDUC,ETHNIC,RACE,GENDER,SPHSERVICE,CMPSERVICE,OPISERVICE,RTCSERVICE,...,ODDFLG,PDDFLG,PERSONFLG,SCHIZOFLG,ALCSUBFLG,OTHERDISFLG,STATEFIP,DIVISION,REGION,CASEID
0,2021,11,4,2,3,1,2,1,2,2,...,0,0,0,0,0,0,1,6,3,20210000001
1,2021,7,-9,3,3,2,2,1,1,2,...,0,0,0,1,0,0,1,6,3,20210000002
2,2021,5,5,4,5,2,1,2,2,2,...,0,0,0,0,0,1,1,6,3,20210000003
3,2021,14,-9,3,3,2,2,1,2,2,...,0,0,0,1,0,0,1,6,3,20210000004
4,2021,4,4,4,5,2,1,2,2,2,...,0,0,0,0,0,0,1,6,3,20210000005

In [5]:
df.describe()

,YEAR,AGE,EDUC,ETHNIC,RACE,GENDER,SPHSERVICE,CMPSERVICE,OPISERVICE,RTCSERVICE,...,ODDFLG,PDDFLG,PERSONFLG,SCHIZOFLG,ALCSUBFLG,OTHERDISFLG,STATEFIP,DIVISION,REGION,CASEID
count,6509025.0,6.509025e+06,6.509025e+06,6.509025e+06,6.509025e+06,6.509025e+06,6.509025e+06,6.509025e+06,6.509025e+06,6.509025e+06,...,6.509025e+06,6.509025e+06,6.509025e+06,6.509025e+06,6.509025e+06,6.509025e+06,6.509025e+06,6.509025e+06,6.509025e+06,6.509025e+06
mean,2021.0,6.904323e+00,-3.238737e+00,2.005490e+00,3.033242e+00,1.508063e+00,1.984172e+00,1.023193e+00,1.965518e+00,1.988732e+00,...,2.382861e-02,1.654088e-02,2.448201e-02,1.104623e-01,5.845899e-02,1.307471e-01,2.801133e+01,5.474895e+00,2.718890e+00,2.021325e+10
std,0.0,4.073035e+00,6.268063e+00,4.417267e+00,4.432505e+00,6.799481e-01,1.248104e-01,1.505171e-01,1.824636e-01,1.055513e-01,...,1.525149e-01,1.275433e-01,1.545401e-01,3.134652e-01,2.346093e-01,3.371236e-01,1.611947e+01,2.594659e+00,1.106567e+00,1.878994e+06
min,2021.0,-9.000000e+00,-9.000000e+00,-9.000000e+00,-9.000000e+00,-9.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,2.021000e+10
25%,2021.0,3.000000e+00,-9.000000e+00,3.000000e+00,3.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.300000e+01,3.000000e+00,2.000000e+00,2.021163e+10
50%,2021.0,7.000000e+00,-9.000000e+00,4.000000e+00,5.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.700000e+01,5.000000e+00,3.000000e+00,2.021325e+10
75%,2021.0,1.000000e+01,4.000000e+00,4.000000e+00,5.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.200000e+01,8.000000e+00,4.000000e+00,2.021488e+10
max,2021.0,1.400000e+01,5.000000e+00,4.000000e+00,6.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,9.900000e+01,9.000000e+00,4.000000e+00,2.021651e+10